### ISSUE TITLE
Don't get into itemBuilder if itemsLength == 0

### ISSUE THREAD

**Issue by baptistesx** [Bdaya-Dev/circular-widgets#7]
It breaks when itemsLength == 0, because it goes into itemBuilder, and then try to access index which doesn't exist...

<img width="275" alt="image" src="https://user-images.githubusercontent.com/9638281/205082697-a736aa51-f1ab-4298-b550-a7a14a97a342.png">

**Comment by ahmednfwela** [comment]
This isn't a problem in the package, since it's safely guarded here https://github.com/Bdaya-Dev/circular-widgets/blob/master/lib/src/circular_widgets.dart#L31

I think the problem is in your code, you have to rebuild the `CircularWidgets` widget when the length changes (using Provider or StreamBuilder for example)
